accounts/urls.py
# accounts/urls.py
from django.urls import path

from accounts.views import SignUpView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/urls.py
from django.urls import path

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = "blog"
urlpatterns = [
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("", BlogListView.as_view(), name="home"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("posts/", include("posts.urls")),
    path("blog/", include("blog.urls")),
    path("pages/", include("pages.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

pages/urls.py
from pages.views import HomePageTemplateView, AboutPageView
from django.urls import path

app_name = "pages"
urlpatterns = [
    path("", HomePageTemplateView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

posts/urls.py
from django.urls import path

from posts.views import HomePageView

app_name = "posts"
urlpatterns = [path("", HomePageView.as_view(), name="home")]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50]

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


# Create your views here.
class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("blog:home")
    template_name = "registration/signup.html"

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blog.models import Post


class BlogListView(ListView):
    model = Post
    template_name = "blog/home.html"


class BlogDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"


class BlogUpdateView(UpdateView):
    model = Post
    template_name = "blog/post_edit.html"
    fields = ["title", "body"]


class BlogCreateView(CreateView):
    model = Post
    template_name = "blog/post_new.html"
    fields = ["title", "author", "body"]


class BlogDeleteView(DeleteView):
    model = Post
    template_name = "blog/post_delete.html"
    success_url = reverse_lazy("blog:home")

pages/views.py
from django.views.generic import TemplateView


class HomePageTemplateView(TemplateView):
    template_name = "pages/home.html"


class AboutPageView(TemplateView):
    template_name = "pages/about.html"

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView

from posts.models import Post


class HomePageView(ListView):
    model = Post

blog/templates/blog/base.html
{% load static %}
<html>
<head>
    <title>
        Django blog
    </title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<header>
    <div class="nav-left">
    <h1>
        <a href="{% url 'blog:home' %}">Django blog</a>
    </h1>
    </div>
    <div class="nav-right">
        <a href="{% url 'blog:post_new' %}">+ New Blog Post</a>
    </div>
</header>
{% if user.is_authenticated %}
    <p>Hi {{ user.username }}!
        <a href="{% url 'logout' %}">Log out</a></p>
{% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Log in</a>
    <a href="{% url 'accounts:signup' %}">Sign up</a></p>

{% endif %}
<div>
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}
{% for post in post_list %}
<div class="post-entry">
  <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
  <p>
  {{ post.body }}
  </p>
</div>
{% endfor %}
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}

{% block content %}
<h1>Delete Post</h1>
<form action="" method="post">
  {% csrf_token %}
  <p>Are you sure, that you want to delete "{{ post.title }}"?</p>
  <input type="submit" value="Confirm">
</form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="post-entry">
  <h2>{{ post.title }}</h2>
  <p>{{ post.body }}</p>
</div>

<a href="{% url 'blog:post_edit' post.pk %}">+ Edit Blog Post</a>
<a href="{% url 'blog:post_delete' post.pk %}">+ Delete Blog Post</a>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}

{% block content %}

<h1>Edit post</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>

{% endblock %}

blog/templates/blog/post_new.html
{% extends "blog/base.html" %}

{% block content %}

<h1>New Post</h1>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>

{% endblock content %}

pages/templates/pages/about.html
{% extends "pages/base.html"%}
{% block content %}

<body><h1>About Page</h1></body>

{% endblock content %}

pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <a href="{% url 'pages:home' %}">Home</a> |
  <a href="{% url 'pages:about' %}">About</a>

</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

pages/templates/pages/home.html
{% extends "pages/base.html"%}
{% block content %}

<body><h1>Homepage</h1></body>

{% endblock content %}

posts/templates/posts/post_list.html
<!-- templates/home.html -->
<h1>Message board homepage</h1>
<ul>
{% for post in post_list %}
<li>{{ post.text }}</li>
{% endfor %}
</ul>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <a href="{% url 'home' %}">Home</a> |
  <a href="{% url 'about' %}">About</a>

</head>
<body>
{% block content %}
{% endblock content %}
</body>
</html>